vich_uploader:
    db_driver: orm
    mappings:
        parc_images:
            uri_prefix: /images/upload
            upload_destination: '%kernel.project_dir%/public/images/upload'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        point_images:
            uri_prefix: /images/upload/point
            upload_destination: '%kernel.project_dir%/public/images/upload/point'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        point_sound:
            uri_prefix: /images/upload/point/sound
            upload_destination: '%kernel.project_dir%/public/images/upload/point/sound'
            namer: Vich\UploaderBundle\Naming\UniqidNamer