vich_uploader:
    db_driver: orm
    mappings:
        parc_images:
            uri_prefix: /images/upload
            upload_destination: '%kernel.project_dir%/public/images/upload'
            namer: Vich\UploaderBundle\Naming\UniqidNamer